### ISSUE TITLE
translation missing:zh-TW.risk_menu and 404 not found Error

### ISSUE THREAD

**Issue by samtptw** [rolesoftware/redrisk#7]
Dear Sir,

My environment:
Environment:
  Redmine version                3.1.2.stable
  Ruby version                   2.2.2-p95 (2015-04-13) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.5.0
  Filesystem  
Redmine plugins:
  a_common_libs                  1.1.4
  clipboard_image_paste          1.10
  progressive_projects_list      1.0.0
  redmine_checklists             3.1.1
  redmine_ckeditor               1.1.0
  redmine_issue_templates        0.1.0
  redmine_issue_todo_lists       1.1.1
  redrisk                        1.0.1
  usability                      2.0.0

When I migrate new Redrisk to 1.0.1 version. The risk menu disappear and URL is 404 not found. 

![missing menu](https://cloud.githubusercontent.com/assets/8186170/11295227/d9092488-8fa4-11e5-809c-af7e66c42aca.jpg)
![404 not found](https://cloud.githubusercontent.com/assets/8186170/11295242/f10abae2-8fa4-11e5-91ab-bbb045751e50.jpg)

I got error message from error log:

---

App 1801 stderr: Started GET "/projects/pre-sales-support/risks" for 10.136.64.168 at 2015-11-20 16:24:05 +0800
App 1801 stderr: 
App 1801 stderr: ActionController::RoutingError (uninitialized constant RisksController):
App 1801 stderr:   activesupport (4.2.4) lib/active_support/inflector/methods.rb:261:in `const_get'
App 1801 stderr:   activesupport (4.2.4) lib/active_support/inflector/methods.rb:261:in`block in constantize'
App 1801 stderr:   activesupport (4.2.4) lib/active_support/inflector/methods.rb:259:in `each'
App 1801 stderr:   activesupport (4.2.4) lib/active_support/inflector/methods.rb:259:in`inject'
App 1801 stderr:   activesupport (4.2.4) lib/active_support/inflector/methods.rb:259:in `constantize'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:72:in`controller_reference'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:62:in `controller'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:41:in`serve'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in`each'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in`call'
App 1801 stderr:   rack-raw-upload (1.1.1) lib/rack/raw_upload.rb:18:in `call'
App 1801 stderr:   rack-openid (1.4.2) lib/rack/openid.rb:98:in`call'
App 1801 stderr:   request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
App 1801 stderr:   rack (1.6.4) lib/rack/etag.rb:24:in`call'
App 1801 stderr:   rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
App 1801 stderr:   rack (1.6.4) lib/rack/head.rb:13:in`call'
App 1801 stderr:   actionpack-xml_parser (1.0.2) lib/action_dispatch/xml_params_parser.rb:16:in `call'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in`call'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
App 1801 stderr:   rack (1.6.4) lib/rack/session/abstract/id.rb:225:in`context'
App 1801 stderr:   rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in`call'
App 1801 stderr:   activerecord (4.2.4) lib/active_record/query_cache.rb:36:in `call'
App 1801 stderr:   activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in`call'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
App 1801 stderr:   activesupport (4.2.4) lib/active_support/callbacks.rb:88:in`**run_callbacks**'
App 1801 stderr:   activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
App 1801 stderr:   activesupport (4.2.4) lib/active_support/callbacks.rb:81:in`run_callbacks'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in`call'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
App 1801 stderr:   railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
App 1801 stderr:   railties (4.2.4) lib/rails/rack/logger.rb:20:in`block in call'
App 1801 stderr:   activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
App 1801 stderr:   activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in`tagged'
App 1801 stderr:   activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
App 1801 stderr:   railties (4.2.4) lib/rails/rack/logger.rb:20:in`call'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
App 1801 stderr:   rack (1.6.4) lib/rack/methodoverride.rb:22:in`call'
App 1801 stderr:   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
App 1801 stderr:   activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in`call'
App 1801 stderr:   actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
App 1801 stderr:   rack (1.6.4) lib/rack/sendfile.rb:113:in`call'
App 1801 stderr:   railties (4.2.4) lib/rails/engine.rb:518:in `call'
App 1801 stderr:   railties (4.2.4) lib/rails/application.rb:165:in`call'
App 1801 stderr:   railties (4.2.4) lib/rails/railtie.rb:194:in `public_send'
App 1801 stderr:   railties (4.2.4) lib/rails/railtie.rb:194:in`method_missing'
App 1801 stderr:   passenger (5.0.8) lib/phusion_passenger/rack/thread_handler_extension.rb:89:in `process_request'
App 1801 stderr:   passenger (5.0.8) lib/phusion_passenger/request_handler/thread_handler.rb:149:in`accept_and_process_next_request'
App 1801 stderr:   passenger (5.0.8) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 1801 stderr:   passenger (5.0.8) lib/phusion_passenger/request_handler.rb:414:in`block (3 levels) in start_threads'
App 1801 stderr:   passenger (5.0.8) lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
App 1801 stderr: 
App 1801 stderr: 
App 1801 stderr: Processing by UsErrorsController#error_404 as HTML
App 1801 stderr:   Parameters: {"id"=>"pre-sales-support"}
App 1801 stderr:   Current user: sam (id=3)
App 1801 stderr:   Rendered plugins/usability/app/views/errors/error_status.html.erb (207.9ms)
## App 1801 stderr: Completed 404 Not Found in 266ms (Views: 208.1ms | ActiveRecord: 6.0ms)

Can you check this error?

```
                                                  Thanks

                                                                                               Sam
```

**Comment by rodrigogirao** [comment]
Redrisk was working in version 1.0?
I will check this error.

**Comment by samtptw** [comment]
I only install Redrisk 1.0.1 version. The old system is : Redmine 3.1.0 and Redrisk 1.0.1.

 I try migrate Redmine from 3.1.0 to 3.1.2. After I migrated Redmine 3.1.2, I run plugin migrate script: rake redmine:plugins:migrate NAME=Redrisk RAILS_ENV=production

. The issue take place in this situation.

**Comment by sidisti** [comment]
Did anyone solve this, we are hitting this problem also. Very frustrating.
Environment:
  Redmine version                3.1.2.stable
  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               PostgreSQL
